name: contact_cards
description: The Contact Cards app
version: 0.0.1-dev

topics:
  - contacts
  - management
  - android
  - ios

platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.5'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  collection: any
  async: any
  meta: any
  path: any

  # Desktop
  window_manager: ^0.3.5

  # Logger
  l: ^4.0.2

  # Transport
  ws: ^0.1.2

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_contacts: ^1.1.7
  freezed_annotation: ^2.4.1
  

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1

  # Codegen
  build_runner: ^2.4.6
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.3.1
  # pubspec_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner: ^5.3.1


flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant
  line_length: 120